### ISSUE TITLE
MAJ dernières versions ?

### ISSUE THREAD

**Issue by Guts** [webgeodatavore/qgis-splash-screens-birthday#1]
Hello @ThomasG77,

Je prévois d'illustrer un petit tuto Géotribu avec ton GIF des splash screens. Pourrais-tu ajouter les dernières versions stp :slightly_smiling_face:  ?

**Comment by ThomasG77** [comment]
Fait. Si tu l'as zappé, le travail d'Étienne peut servir également si tu viens à parler de roadmap https://github.com/Gustry/qgis-roadmap-project

**Comment by Guts** [comment]
> Fait. 

Merci.

> Si tu l'as zappé, le travail d'Étienne peut servir également si tu viens à parler de roadmap https://github.com/Gustry/qgis-roadmap-project

J'avais vu et relayé à l'époque mais là c'est pas mon sujet.
